# Generated by Django 4.0 on 2022-05-08 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favourites',
            field=models.ManyToManyField(related_name='video_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
