# Generated by Django 4.0 on 2022-05-08 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0002_video_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='video_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
