# Generated by Django 4.0 on 2022-05-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
        ('video', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='myuser.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='video.video', unique=True)),
            ],
        ),
    ]
