# Generated by Django 4.0 on 2022-05-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='video.video'),
        ),
    ]
